---
title: "Using Filter - Lab"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
    fig_caption: false
    css: css/textbook.min.css
runtime: shiny_prerendered
description: >
  filter_lab Description.
---

<!-- Code for including shinyJS, currently used for toggling css classes toggleClass() | https://deanattali.com/shinyjs/advanced#usage-prerendered -->
```{r, echo=FALSE}
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```
```{r, context="server"}
shinyjs::useShinyjs(html = TRUE)
```
<script src="shinyjs/inject.js"></script>

<!-- End Code for shinyJs -->
```{r setup, include=FALSE}
library(learnr)
gradethis::gradethis_setup()

##Setup Homework Grade Tracker - keeps track of a student's name, grade, and answers to each homework problem
## WARNING: The default values are set inside the "session_start" event handler, which is inside of homework.Rmd
hmw_info <- NULL

#Uncomment to view all the Learnr events and their data. The data field is not well documented, so this a handy way to view everything
#new_recorder <- function(tutorial_id, tutorial_version, user_id, event, data) {
   #cat("Original: \n", tutorial_id, " (", tutorial_version, "): ", user_id, ", ", event, "\nData:\n", sep = "")
   #print(data)
#}
#options(tutorial.event_recorder = new_recorder)

library(tidyverse)
library(shinyjs)
library(reactable)

addResourcePath("SharedResources", "../SharedResources")#Add access to a shared set of images. Like the banner for the farm dataset
farm_data <- read_csv("../SharedResources/datasets/FarmInventory/data.csv", col_types="ccddffi"); #Homework dataset

knitr::opts_chunk$set(error = FALSE, message = FALSE)
```

---

## Practice Problem 1
Finish the code block, so that ....
```{r filter_lab_practice1, exercise = TRUE, exercise.blanks = "___+"}

```

```{r filter_lab_practice1-solution}

```

```{r filter_lab_practice1-check}
grade_result(
  pass_if(~identical(.result, TRUE))
)
```

---
